# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ab0ec2766e1f8d2c8ecccd1655889bbd387d6844c79634b0a5a49a2922d6591540e1f7fe3f0e9922ff2cc7695c2790357a4e024ff62ec09dbf7f8be29dd3604

test:
  secret_key_base: a869a550572db05da4e2ef1efac1ccdc77c9ab7622c5a5e10a681e791b4ad7557c9a5af9a8da4d3078eeb1cb470a8dc6553d9a113e2153c1457e7b512c179bf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
